name: Tic-Tac-Toe Game Update

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Game action (move or reset)'
        required: true
        default: 'reset'
        type: choice
        options:
        - reset
        - move
      row:
        description: 'Row for move (0-2)'
        required: false
        type: string # Принимаем как строку, чтобы Python мог обработать None/пустые строки
      col:
        description: 'Column for move (0-2)'
        required: false
        type: string # Аналогично

jobs:
  update_game:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Необходимо для коммита изменений в README и board.json
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Можете указать вашу предпочтительную версию Python 3.x

      - name: Run game logic
        env:
          GITHUB_REPOSITORY: ${{ github.repository }} # Передаем имя репозитория в скрипт
        shell: bash
        run: |
          echo "Запуск GitHub Action для игры Крестики-Нолики"
          echo "Действие: ${{ github.event.inputs.action }}"
          echo "Строка: ${{ github.event.inputs.row }}"
          echo "Колонка: ${{ github.event.inputs.col }}"

          CMD="python game.py --action ${{ github.event.inputs.action }}"

          if [[ "${{ github.event.inputs.action }}" == "move" ]]; then
            # Для 'move' добавляем row и col, если они предоставлены
            # Скрипт Python теперь сам будет обрабатывать, если они пустые или некорректные
            if [[ -n "${{ github.event.inputs.row }}" ]]; then
              CMD="$CMD --row \"${{ github.event.inputs.row }}\""
            fi
            if [[ -n "${{ github.event.inputs.col }}" ]]; then
              CMD="$CMD --col \"${{ github.event.inputs.col }}\""
            fi
          fi
          
          echo "Выполняемая команда: $CMD"
          eval $CMD # Используем eval, чтобы кавычки вокруг значений row/col корректно обработались

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md board.json
          
          # Проверяем, есть ли изменения перед коммитом
          if git diff --staged --quiet; then
            echo "Изменений для коммита нет."
          else
            COMMIT_MSG="🎮 Tic-Tac-Toe: Обновление состояния игры"
            if [[ "${{ github.event.inputs.action }}" == "move" ]]; then
              COMMIT_MSG="$COMMIT_MSG (Ход: ${{ github.event.inputs.row }},${{ github.event.inputs.col }})"
            elif [[ "${{ github.event.inputs.action }}" == "reset" ]]; then
              COMMIT_MSG="$COMMIT_MSG (Сброс игры)"
            fi
            git commit -m "$COMMIT_MSG"
            # Принудительный пуш может быть нужен, если README обновляется очень часто и есть конфликты
            # Но обычно достаточно обычного push. Попробуйте сначала без --force.
            git push 
            echo "Изменения закоммичены и отправлены."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}