name: Tic-Tac-Toe Game Update

on:
  workflow_dispatch: # Позволяет запускать вручную и по ссылкам
    inputs:
      action:
        description: 'Game action (move or reset)'
        required: true
        default: 'reset'
      row:
        description: 'Row for move (0-2)'
        required: false
      col:
        description: 'Column for move (0-2)'
        required: false
  # Можно добавить schedule для автоматического обновления, если игра "портится" со временем
  # schedule:
  #  - cron: '0 * * * *' # Каждый час, например

jobs:
  update_game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run game logic
        shell: bash # Указываем оболочку явно
        run: |
          echo "Action: ${{ github.event.inputs.action }}"
          echo "Row: ${{ github.event.inputs.row }}"
          echo "Col: ${{ github.event.inputs.col }}"

          if [ "${{ github.event.inputs.action }}" = "move" ]; then
            # Для 'move' row и col должны быть предоставлены
            if [ -z "${{ github.event.inputs.row }}" ] || [ -z "${{ github.event.inputs.col }}" ]; then
              echo "::error::Action 'move' requires row and col inputs."
              exit 1
            fi
            python game.py --action "${{ github.event.inputs.action }}" --row "${{ github.event.inputs.row }}" --col "${{ github.event.inputs.col }}"
          elif [ "${{ github.event.inputs.action }}" = "reset" ]; then
            python game.py --action "${{ github.event.inputs.action }}"
          else
            echo "::error::Unknown action: ${{ github.event.inputs.action }}"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md board.json
          # Проверяем, есть ли изменения перед коммитом
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "🎮 Tic-Tac-Toe: Update game state (Action: ${{ github.event.inputs.action }})"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}